"""Phase 4a: Security and Banking models

Revision ID: 83362d8303fc
Revises: 2a4523105a35
Create Date: 2026-03-22 22:28:11.366714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83362d8303fc'
down_revision: Union[str, None] = '2a4523105a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number_masked', sa.String(length=32), nullable=False),
    sa.Column('ifsc_code', sa.String(length=32), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.add_column('tokens', sa.Column('remaining_value', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('users', sa.Column('transaction_pin_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('kyc_status', sa.String(length=32), server_default='pending', nullable=False))
    op.add_column('users', sa.Column('app_lock_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'app_lock_enabled')
    op.drop_column('users', 'kyc_status')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'transaction_pin_hash')
    op.drop_column('tokens', 'remaining_value')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
